#-------------------------------------------------------------------------------
#						Search all libraries on the system
#-------------------------------------------------------------------------------
## Use cmake package to find module
if (Linux)
    find_package(PCAP)
    find_package(LibXml2)
endif()
find_package(Gettext) # translation tool
if(EXISTS ${PROJECT_SOURCE_DIR}/.git)
    find_package(Git)
endif()
find_package(LibLZMA)

# Using find_package OpenGL without either setting your opengl preference to GLVND or LEGACY
# is deprecated as of cmake 3.11.
set(OpenGL_GL_PREFERENCE GLVND)
find_package(OpenGL)
find_package(PNG)
set(wxWidgets_FOUND 1)
set(wxWidgets_USE_FILE 3rdparty/wxwidgets3.0/UsewxWidgets.cmake)
find_package(ZLIB)

## Use pcsx2 package to find module
if (NOT MSVC)
   include(FindLibc)
endif()

## Only needed by the extra plugins
if(EXTRA_PLUGINS)
    include(FindCg)
    include(FindGlew)
    find_package(JPEG)
endif()

## Use CheckLib package to find module
include(CheckLib)
if(Linux)
    check_lib(EGL EGL EGL/egl.h)
    check_lib(X11_XCB X11-xcb X11/Xlib-xcb.h)
    check_lib(AIO aio libaio.h)
    # There are two udev pkg config files - udev.pc (wrong), libudev.pc (correct)
    # When cross compiling, pkg-config will be skipped so we have to look for
    # udev (it'll automatically be prefixed with lib). But when not cross
    # compiling, we have to look for libudev.pc. Argh. Hence the silliness below.
    if(CMAKE_CROSSCOMPILING)
        check_lib(LIBUDEV udev libudev.h)
    else()
        check_lib(LIBUDEV libudev libudev.h)
    endif()
endif()

if(UNIX)
      pkg_check_modules(PC_GLIB QUIET glib-2.0)
      find_library(GLIB_LIBRARIES NAMES glib-2.0 HINTS ${PC_GLIB_LIBRARY_DIRS})
      get_filename_component(_GLIB_LIBRARY_DIR ${GLIB_LIBRARIES} PATH)
      find_path(GLIBCONFIG_INCLUDE_DIR NAMES glibconfig.h HINTS ${PC_LIBRARY_DIRS} ${_GLIB_LIBRARY_DIR} PATH_SUFFIXES glib-2.0/include)
      find_path(GLIB_INCLUDE_DIR NAMES glib.h HINTS ${PC_GLIB_INCLUDE_DIRS} PATH_SUFFIXES glib-2.0)
      set(GLIB_INCLUDE_DIRS ${GLIB_INCLUDE_DIR} ${GLIBCONFIG_INCLUDE_DIR})
      find_library(GLIB_GIO_LIBRARIES NAMES gio-2.0 HINTS ${_GLIB_LIBRARY_DIR})
endif()

#----------------------------------------
#		    Use system include
#----------------------------------------
if(UNIX)
	if(X11_FOUND)
		include_directories(${X11_INCLUDE_DIR})
	endif()
endif()

if(CG_FOUND)
	include_directories(${CG_INCLUDE_DIRS})
endif()

if(JPEG_FOUND)
	include_directories(${JPEG_INCLUDE_DIR})
endif()

if(GLEW_FOUND)
    include_directories(${GLEW_INCLUDE_DIR})
endif()

if(OPENGL_FOUND)
	include_directories(${OPENGL_INCLUDE_DIR})
endif()

if(wxWidgets_FOUND)
	include(${wxWidgets_USE_FILE})
endif()

if(PCAP_FOUND)
	include_directories(${PCAP_INCLUDE_DIR})
endif()

if(LIBXML2_FOUND)
	include_directories(${LIBXML2_INCLUDE_DIRS})
endif()

if(ZLIB_FOUND)
	include_directories(${ZLIB_INCLUDE_DIRS})
else()
   set(ZLIB_FOUND TRUE)
   set(ZLIB_LIBRARIES z)
   add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/zlib)
   include_directories(${CMAKE_SOURCE_DIR}/3rdparty)
   include_directories(${CMAKE_SOURCE_DIR}/3rdparty/zlib)
endif()

if(NOT LIBLZMA_FOUND)
   set(LIBLZMA_FOUND 1)
   add_definitions(-DLZMA_API_STATIC)
   set(LIBLZMA_LIBRARIES lzma)
   add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/xz)
endif()

if(MSVC)
   add_definitions(-DPTW32_STATIC_LIB)
#   add_definitions(-D__CLEANUP_SEH)
   add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/pthreads4w)
   include_directories(${CMAKE_SOURCE_DIR}/3rdparty/pthreads4w/include)
   add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/baseclasses)
#   include_directories(${CMAKE_SOURCE_DIR}/3rdparty/baseclasses)
endif()

set(ACTUALLY_ENABLE_TESTS ${ENABLE_TESTS})
if(ENABLE_TESTS)
	if(NOT EXISTS "${CMAKE_SOURCE_DIR}/3rdparty/gtest/CMakeLists.txt")
		message(WARNING "ENABLE_TESTS was on but gtest was not found, unit tests will not be enabled")
		set(ACTUALLY_ENABLE_TESTS Off)
	endif()
endif()

#----------------------------------------
#  Use  project-wide include directories
#----------------------------------------
include_directories(${CMAKE_SOURCE_DIR}/common/include
					${CMAKE_SOURCE_DIR}/common/include/Utilities
					${CMAKE_SOURCE_DIR}/common/include/x86emitter
                    # File generated by Cmake
                    ${CMAKE_BINARY_DIR}/common/include
                    )

#----------------------------------------
# Check correctness of the parameter
# Note: wxWidgets_INCLUDE_DIRS must be defined
#----------------------------------------
include(ApiValidation)

WX_vs_SDL()

# Blacklist bad GCC
if(GCC_VERSION VERSION_EQUAL "7.0" OR GCC_VERSION VERSION_EQUAL "7.1")
    GCC7_BUG()
endif()

if((GCC_VERSION VERSION_EQUAL "9.0" OR GCC_VERSION VERSION_GREATER "9.0") AND GCC_VERSION LESS "9.2")
    message(WARNING "
    It looks like you are compiling with 9.0.x or 9.1.x. Using these versions is not recommended,
    as there is a bug known to cause the compiler to segfault while compiling. See patch
    https://gitweb.gentoo.org/proj/gcc-patches.git/commit/?id=275ab714637a64672c6630cfd744af2c70957d5a
    Even with that patch, compiling with LTO may still segfault. Use at your own risk!
    This text being in a compile log in an open issue may cause it to be closed.")
endif()

find_package(fmt "7.0.3" QUIET)
if(NOT fmt_FOUND)
    if(EXISTS "${CMAKE_SOURCE_DIR}/3rdparty/fmt/fmt/CMakeLists.txt")
        message(STATUS "No system fmt was found. Using bundled")
        add_subdirectory(3rdparty/fmt/fmt)
    else()
        message(FATAL_ERROR "No system or bundled fmt was found")
    endif()
else()
    message(STATUS "Found fmt: ${fmt_VERSION}")
endif()

add_subdirectory(3rdparty/libchdr EXCLUDE_FROM_ALL)
include_directories(3rdparty/libchdr/include)
add_subdirectory(3rdparty/yaml-cpp EXCLUDE_FROM_ALL)
include_directories(3rdparty/yaml-cpp/include)
